name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "RepoName=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
          echo ${{ env.RepoName }}

      - name: Display RepoName
        run: echo "RepoName is $RepoName"
        env:
          RepoName: ${{ env.RepoName }}
