name: Repository dispatch run

on:
  workflow_dispatch:

jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Api
        run: |
          TOKEN=${{ secrets.MY_PAT }}

          curl \
            -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/pandrabox/vpm/dispatches \
            -d '{"event_type":"on-demand-test","client_payload":{"env": "dev"}}'
